---
- name: destroy bastion host
  hosts: bastion
  connection: local
  tasks:
  - cs_instance:
      name: "{{ inventory_hostname_short }}"
      state: expunged

- name: destroy VMs
  hosts: cloud-vm
  connection: local
  tasks:
  - cs_instance:
      name: "{{ inventory_hostname_short }}"
      state: expunged

# - name: cleanup common stuff
#   hosts: localhost
#   connection: local
#   tasks:
#   - cs_template:
#       name: trusty-server-cloudimg-amd64
#       state: absent
