---
- name: setup cloud
  hosts: localhost
  connection: local
  tasks:
  - name: upload ssh public key
    cs_sshkeypair:
      name: default_key
      public_key: "{{ lookup('file', 'id_rsa.pub') }}"

- name: setup bastion host
  hosts: bastion
  connection: local
  tasks:
  - name: create and run bastion VM
    cs_instance:
      name: "{{ inventory_hostname_short }}"
      template: "{{ template }}"
      service_offering: 1cpu/1gb_ardigen_linux
      ssh_key: default_key
      state: started
  - name: setup port forwarding
    cs_portforward:
      ip_address: "{{ public_ip }}"
      vm: "{{ inventory_hostname_short }}"
      public_port: 22
      private_port: 22
      open_firewall: true
  - name: assing IP to the inventory
    set_fact: ansible_ssh_host="{{ public_ip }}"
  - name: show VM IP
    debug: msg="VM {{ inventory_hostname }} "{{ public_ip }}""
