---
- name: setup VMs
  hosts: cloud-vm
  connection: local
  tasks:
  - name: create and run VMs
    cs_instance:
      name: "{{ inventory_hostname_short }}"
      template: "{{ template }}"
      service_offering: "{{ service_offering }}"
      disk_offering: "{{ disk_offering }}"
      ssh_key: default_key
      state: started
    register: vm
  - name: assing IP to the inventory
    set_fact: ansible_ssh_host="{{ vm.default_ip }}"
  - name: show VM IP
    debug: msg="VM {{ inventory_hostname }} {{ vm.default_ip }}"

- name: configure VMs
  hosts: cloud-vm
  user: ubuntu
  become: yes
  tasks:
  - apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
  - apt_repository: "repo='deb https://apt.dockerproject.org/repo {{ ansible_distribution | lower }}-{{ ansible_distribution_release }} main'"
  - name: install packages
    apt:
      name: "{{ item }}"
      update_cache: yes
      cache_valid_time: 3600
    with_items:
      - "linux-image-extra-{{ ansible_kernel }}"
      - apparmor
      - apt-transport-https
      - ca-certificates
      - curl
      - docker-engine
      - git
      - python-pip
  - pip: name=docker-py version=1.2.3
  - name: start docker
    service: name=docker state=started enabled=yes
  - name: create container
    docker:
      name: test_1
      image: ubuntu
      state: started
      command: sleep 1d
